const API='https://api.mercadolibre.com/sites/MLB/search',LOCAL_API='/api/search',K='promozone-v1';
const defaultSettings={channelName:'PromoZone',channelUrl:'https://whatsapp.com/channel/0029Vb8atiKIXnliGqAMh33R',footer:'⚡ Oferta encontrada pela PromoZone\n💚 Entre no canal para receber mais oportunidades!',template:''};
const samples=[{id:'demo-1',title:'Oferta de exemplo — Fone Bluetooth',price:89.9,original_price:149.9,thumbnail:'https://http2.mlstatic.com/D_NQ_NP_2X_959920-MLA85467878971_062025-F.webp',permalink:'https://www.mercadolivre.com.br/',condition:'new',shipping:{free_shipping:true}},{id:'demo-2',title:'Oferta de exemplo — Air Fryer',price:249.9,original_price:399.9,thumbnail:'https://http2.mlstatic.com/D_NQ_NP_2X_754033-MLU74356771155_022024-F.webp',permalink:'https://www.mercadolivre.com.br/',condition:'new',shipping:{free_shipping:true}}];
let settings={...defaultSettings,...JSON.parse(localStorage.getItem(K+'settings')||'{}')},queue=JSON.parse(localStorage.getItem(K+'queue')||'[]'),items=[];
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n),off=p=>p.original_price?Math.round((1-p.price/p.original_price)*100):0;
const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
function persist(){localStorage.setItem(K+'settings',JSON.stringify(settings));localStorage.setItem(K+'queue',JSON.stringify(queue))}
function link(p){return p.affiliateLink?.trim()||(settings.template.trim()?settings.template.replaceAll('{{url}}',encodeURIComponent(p.permalink)).replaceAll('{{id}}',p.id).replaceAll('{{title}}',encodeURIComponent(p.title)):p.permalink)}
function text(p){return `🔥 *${p.title}*\n\n💸 Por *${money(p.price)}*${off(p)?` (${off(p)}% OFF)`:''}${p.original_price?`\nDe ~${money(p.original_price)}~`:''}\n${p.shipping?.free_shipping?'🚚 Frete grátis\n':''}\n🔗 ${link(p)}\n\n${settings.footer}`}
function renderQueue(){const host=$('queueList');$('queueCount').textContent=queue.length;$('clear').disabled=!queue.length;if(!queue.length){host.innerHTML='<div class="empty">✓<br><br>Nenhuma oferta escolhida ainda.</div>';return}host.innerHTML=queue.map(p=>`<div class="qitem"><img src="${p.thumbnail.replace('http:','https:')}"><div><h4>${esc(p.title)}</h4><strong>${money(p.price)}</strong></div><button data-id="${p.id}">×</button></div>`).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>{queue=queue.filter(p=>p.id!==b.dataset.id);persist();renderQueue()})}
function edit(p){$('preview').innerHTML=`<img src="${p.thumbnail.replace('http:','https:')}"><div><h3>${esc(p.title)}</h3><p>${money(p.price)}${off(p)?` · ${off(p)}% OFF`:''}</p></div>`;$('message').value=text(p);$('editor').showModal()}
function render(){const host=$('grid');host.innerHTML='';items.forEach(p=>{const n=$('card').content.cloneNode(true),card=n.querySelector('.card');card.querySelector('img').src=p.thumbnail.replace('http:','https:');card.querySelector('span').textContent=off(p)?`${off(p)}% OFF`:'OFERTA';card.querySelector('small').textContent=p.condition==='new'?'Novo':p.condition;card.querySelector('h3').textContent=p.title;card.querySelector('strong').textContent=money(p.price);card.querySelector('del').textContent=p.original_price?money(p.original_price):'';card.querySelector('p').textContent=p.shipping?.free_shipping?'Frete grátis':'';const b=card.querySelector('button');b.textContent=queue.some(x=>x.id===p.id)?'✓':'+';b.onclick=()=>{if(!queue.some(x=>x.id===p.id)){queue.unshift(p);persist();renderQueue()}edit(p)};host.appendChild(n)})}
async function catalogRequest(query){const response=await fetch(LOCAL_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:query,accessToken:settings.mlAccessToken||''})});if(!response.ok){const info=await response.json().catch(()=>({}));throw Error(info.error||`HTTP ${response.status}`)}const data=await response.json();if(!Array.isArray(data.results))throw Error('Resposta inválida');return data}
async function search(){const q=$('query').value.trim()||'ofertas';$('status').textContent='Consultando catálogo e fotos reais do Mercado Livre…';$('grid').innerHTML='';try{const data=await catalogRequest(q),min=Number($('min').value)||0,max=Number($('max').value)||Infinity,d=Number($('discount').value)||0;items=data.results.filter(p=>p.price>=min&&p.price<=max&&off(p)>=d&&(!$('shipping').checked||p.shipping?.free_shipping));$('count').textContent=`${items.length} resultados`;$('status').textContent=items.length?'Produtos e fotos reais carregados do Mercado Livre. Clique em + para revisar uma oferta.':'A busca funcionou, mas nenhum produto passou pelos filtros. Tente reduzir o desconto mínimo.';render()}catch{items=[];$('count').textContent='0 resultados';$('status').textContent=settings.mlAccessToken?'O token foi recusado ou expirou. Gere outro token no Mercado Livre e salve em Configurações.':'Conecte seu token do Mercado Livre em Configurações para carregar produtos e fotos reais.';render()}}
$('form').onsubmit=e=>{e.preventDefault();search()};$('refresh').onclick=search;$('clear').onclick=()=>{queue=[];persist();renderQueue()};$('settings').onclick=()=>{$('channelName').value=settings.channelName;$('channelUrl').value=settings.channelUrl;$('footer').value=settings.footer;$('template').value=settings.template;$('config').showModal()};$('save').onclick=()=>{settings={channelName:$('channelName').value||defaultSettings.channelName,channelUrl:$('channelUrl').value||defaultSettings.channelUrl,footer:$('footer').value,template:$('template').value};persist();$('config').close()};$('copy').onclick=async()=>{await navigator.clipboard.writeText($('message').value);$('copy').textContent='Copiado ✓';setTimeout(()=>$('copy').textContent='Copiar mensagem',1400)};$('channel').onclick=()=>window.open(settings.channelUrl,'_blank','noopener');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());renderQueue();search();
